version: '3'
services:
  mailpile:
    container_name: mailpile
    image: rroemhild/mailpile
    volumes:
      - '/some/local/path:/root/.local/share/Mailpile'
      - '/another/local/path:/root/.gnupg'
    ports:
      - '33411:33411'
